[versions]

# plugins
shadow = "8.3.3"

socialismus = "2.0.0-RC1"

# compile time processing
lombok = "1.18.34"

# general
guice = "7.0.0"
adventure = "4.17.0"
jackson = "2.17.2"

# cloud
cloud-core = "2.0.0"

[libraries]

socialismus = { group = "com.github.whereareiam", name = "Socialismus", version.ref = "socialismus" }

# compile time processing
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# general
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
adventure = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
jackson = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }

# cloud
cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud-core" }
cloud-annotations = { group = "org.incendo", name = "cloud-annotations", version.ref = "cloud-core" }

[bundles]

cloud = ["cloud-core", "cloud-annotations"]

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }